image: Visual Studio 2017
configuration: Release
build:
  verbosity: minimal
  
after_build:
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\Warcraft II\Release\Warcraft II.exe" %APPVEYOR_BUILD_FOLDER%\Warcraft II\Game
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\README.md" %APPVEYOR_BUILD_FOLDER%\Warcraft II\Game
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\LICENSE" %APPVEYOR_BUILD_FOLDER%\Warcraft II\Game
- 7z a WarcraftII_The_Stolen_Artifacts.zip %APPVEYOR_BUILD_FOLDER%\Warcraft II\Game

artifacts:
  - path: WarcraftII_The_Stolen_Artifacts.zip
  
deploy:
  - provider: GitHub
    release: Warcraft II The Stolen Artifacts v$(appveyor_build_version)
    artifact: "WarcraftII_The_Stolen_Artifacts.zip"
    auth_token:
      secure: gLO58slheZU//xXhhrABM+3RfrqKEi3pshUKgqjQLgGFSEElJqUDgAsXrpQhi6Sl
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: false

